# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-26 19:14
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0004_auto_20170513_2016'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='professor',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='professor',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='student',
            name='dni',
        ),
        migrations.AddField(
            model_name='professor',
            name='user',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='professor', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
